version: '3.4'
services:
  memcached:
    image: memcached:1.4
  mysql:
    image: mysql:5.7
    env_file:
      - ./mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - ./misc/data:/var/lib/mysql
      - ./mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    networks:
      - web
  nginx:
    build: ./nginx
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx/public:/var/www/html
    networks:
       - web
  php:
    build: ./php/v1
    depends_on:
      - mysql
    volumes:
      - ./php/v1/public:/var/www/html
    networks:
       - web
    env_file:
      - ./php/v1/.env
networks:
  web:
    driver: bridge
