version: '3.4'
services:
  nginx:
    build: ./nginx
    depends_on:
      #- php
      - slim
    ports:
      - "80:80"
    volumes:
      - ./nginx/public:/var/www/public
      ##デバック用にローカルファイルのマウント
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    networks:
       - web
  mysql:
    image: mysql:5.7
    env_file:
      - ./mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - ./misc/data:/var/lib/mysql
      - ./mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    networks:
      - web
  #php:
  #  build: ./php/
  #  depends_on:
  #    - mysql
  #  volumes:
  #    - ./php/public:/var/www/public
  #  networks:
  #     - web
  #  env_file:
  #    - ./php/.env
  slim:
    build: ./slim
    networks:
      - web
    env_file:
      - ./slim/.env
    volumes:
      - ./slim/sample:/var/www/html
networks:
  web:
    driver: bridge
