version: '3.4'
services:
  memcached:
    image: memcached:1.4
  mysql:
    image: mysql:5.7
    env_file:
      - ./mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - ./misc/data:/var/lib/mysql
      - ./mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    networks:
      - web
  nginx:
    build: ./nginx
    depends_on:
      - php
      - slim
    ports:
      - "80:80"
    volumes:
      - ./nginx/public:/var/www/public
    networks:
       - web
  php:
    build: ./php/v1
    depends_on:
      - mysql
    volumes:
      - ./php/v1/public:/var/www/public
    networks:
       - web
    env_file:
      - ./php/v1/.env
  slim:
    build: ./php/v2
    environment:
      docker: "true"
    networks:
      - web
    ports:
      - 8080:8080
    env_file:
      - ./php/v2/.env
    volumes:
       - ./php/v2/sample:/var/www
networks:
  web:
    driver: bridge
